import { ProductCardApi } from './product-card/product-card-interface';

export const mockProducts: ProductCardApi[] = [
  {
    id: '1',
    name: 'Monitor',
    description: '27-inch 4K Monitor',
    price: 499.99,
    remainingOnStock: 5,
    onStock: true,
    imageUrl: './productimages/monitor.jpg',
  },
  {
    id: '2',
    name: 'Keyboard',
    description: 'Mechanical Keyboard',
    price: 129.99,
    remainingOnStock: 10,
    onStock: true,
    imageUrl: './productimages/keyboard.jpg',
  },
  {
    id: '3',
    name: 'Mouse',
    description: 'Ergonomic Mouse',
    price: 49.99,
    remainingOnStock: 8,
    onStock: true,
    imageUrl: './productimages/mouse.jpg',
  },
  {
    id: '4',
    name: 'Headset',
    description: 'Noise-canceling Headset',
    price: 199.99,
    remainingOnStock: 3,
    onStock: true,
    imageUrl: './productimages/headset.jpg',
  },
  {
    id: '5',
    name: 'Webcam',
    description: 'High-definition Webcam',
    price: 79.99,
    remainingOnStock: 15,
    onStock: true,
    imageUrl: './productimages/webcam.jpg',
  },
  {
    id: '6',
    name: 'Printer',
    description: 'Laser Printer',
    price: 299.99,
    remainingOnStock: 2,
    onStock: true,
    imageUrl: './productimages/printer.jpg',
  },
  {
    id: '7',
    name: 'Scanner',
    description: 'Document Scanner',
    price: 149.99,
    remainingOnStock: 5,
    onStock: true,
    imageUrl: './productimages/scanner.jpg',
  },
  {
    id: '8',
    name: 'Projector',
    description: 'High-brightness Projector',
    price: 999.99,
    remainingOnStock: 1,
    onStock: true,
    imageUrl: './productimages/projector.jpg',
  },
  {
    id: '9',
    name: 'Desk',
    description: 'Adjustable Height Desk',
    price: 449.99,
    remainingOnStock: 3,
    onStock: true,
    imageUrl: './productimages/desk.jpg',
  },
  {
    id: '10',
    name: 'Chair',
    description: 'Ergonomic Office Chair',
    price: 399.99,
    remainingOnStock: 7,
    onStock: true,
    imageUrl: './productimages/chair.jpg',
  },
  {
    id: '11',
    name: 'Laptop Stand',
    description: 'Adjustable Laptop Stand',
    price: 29.99,
    remainingOnStock: 12,
    onStock: true,
    imageUrl: './productimages/laptop-stand.jpg',
  },
  {
    id: '12',
    name: 'Mouse Pad',
    description: 'Large Gaming Mouse Pad',
    price: 19.99,
    remainingOnStock: 20,
    onStock: true,
    imageUrl: './productimages/mouse-pad.jpg',
  },
  {
    id: '16',
    name: 'External Hard Drive',
    description: '2TB External Hard Drive',
    price: 99.99,
    remainingOnStock: 3,
    onStock: true,
    imageUrl: './productimages/harddrive.jpg',
  },
  {
    id: '17',
    name: 'Printer Ink Cartridge',
    description: 'Black Ink Cartridge',
    price: 29.99,
    remainingOnStock: 10,
    onStock: true,
    imageUrl: './productimages/placeholder.jpg',
  },
  {
    id: '20',
    name: 'Whiteboard',
    description: 'Magnetic Whiteboard',
    price: 99.99,
    remainingOnStock: 4,
    onStock: true,
    imageUrl: './productimages/whiteboard.jpg',
  },
];
